language: python
linux_before_install: &linuxbefore
  - sudo apt-get install -y texlive-latex-base pgf texlive-pictures texlive-latex-extra
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran

jobs:
  include:
    - name:  "Python 3.6 on Xenial Linux"
      dist: xenial
      before_install: *linuxbefore
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      dist: xenial
      before_install: *linuxbefore
      python: 3.7
    - name: "Python 3.8 on Xenial Linux"
      dist: xenial
      before_install: *linuxbefore
      python: 3.8
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install xelatex
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --editable ".[dev]"
script:
  - python3 manage.py test
after_success:
  - coverage run --source=survey --omit=survey/migrations/* ./manage.py test
  - coverage html
  - coveralls
